"""empty message

Revision ID: de9941a576c6
Revises: None
Create Date: 2016-09-09 18:58:16.949997

"""

# revision identifiers, used by Alembic.
revision = 'de9941a576c6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
